### ISSUE TITLE
Swing angle automation resets temperature

### ISSUE THREAD

**Issue by Byter09** [mill1000/midea-ac-py#121]
Hello again!

I've been playing around with automation after #118 wasn't a real issue, and I've noticed a weird behaviour. I have the following automation:

```yaml
alias: Klimaanlage
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.btr_ac
    attribute: current_temperature
    for:
      hours: 0
      minutes: 3
      seconds: 0
  - platform: state
    entity_id:
      - climate.btr_ac
    attribute: temperature
    for:
      hours: 0
      minutes: 0
      seconds: 10
condition: []
action:
  - if:
      - condition: numeric_state
        entity_id: climate.btr_ac
        attribute: temperature
        below: sensor.btr_ac_indoor_temperature
    then:
      - device_id: ea73cdbd9092d9ba3f85d2391ba4ca2c
        domain: climate
        entity_id: 45946b956601e3ce6f2bab2ce2a5fdc5
        type: set_hvac_mode
        hvac_mode: auto
        enabled: true
      - device_id: ea73cdbd9092d9ba3f85d2391ba4ca2c
        domain: select
        entity_id: 83aae9c863bff5fe212b5b3bd2772612
        type: select_option
        option: pos_5
    else:
      - device_id: ea73cdbd9092d9ba3f85d2391ba4ca2c
        domain: climate
        entity_id: 45946b956601e3ce6f2bab2ce2a5fdc5
        type: set_hvac_mode
        hvac_mode: "off"
        enabled: true
    enabled: true
mode: restart
```

Basically, when the temperature is above the target temperature, turn on the AC in auto mode, otherwise turn it off.

When turning it on, I also set the swing angle. This is specific to my setup and where the AC is in my room, and is quite important to have it work effectively.

However, I noticed the AC turning off when I set the target temperature to 20°C. I was wondering why, so I took apart the automation and tested each action separately. The last one I tried was the swing angle setting because I couldn't believe it at first. But after several tries, and various ways to set the angle, no matter what I did, it always reset the temperature to 21°C, which caused the automation to re-trigger and turn off the whole AC again.

I am quite unsure what's going on there and I'm not sure this is just some weird HA quirk again. If you need anything to fix this or need me to try something, don't hesitate to ask.

Again, thanks for this wonderful integration 😄
