### ISSUE TITLE
in automation Fan Mode doesnt react

### ISSUE THREAD

**Issue by higgy-de** [mill1000/midea-ac-py#269]
hello 
when i try to make a auto-start of my midea, the mode of the RPM of the fan always takes the 
rpm from last time of use, doesnt change to my (wish 40% rpm) of the fan, here is the yaml :  

```
alias: Wohnzimmer_heizen
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.shelly_h_t_wz_temperature
    below: 25
    for:
      hours: 0
      minutes: 0
      seconds: 0
conditions:
  - condition: time
    after: "14:00:00"
    before: "02:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
actions:
  - device_id: 2ea4b7557db18b7f4a9cabc3b5da3008
    domain: climate
    entity_id: 59b659b224d19aa0cff34000ced7dae0
    type: set_hvac_mode
    hvac_mode: heat
  - device_id: 2ea4b7557db18b7f4a9cabc3b5da3008
    domain: number
    entity_id: 773c504ac12a4613b52a0403c37e5302
    type: set_value
    value: 40
mode: single
```

![heizen](https://github.com/user-attachments/assets/a1ef3d6e-929a-4af1-8857-4d70a45f82f1)

Also a question, how do I tell him the temperatur ( e.g. 27° ) in Home Assistant automations ?
