### ISSUE TITLE
能添加空调设备，但是不能控制设备，控制报错

### ISSUE THREAD

**Issue by muyeyong** [mill1000/midea-ac-py#335]
错误信息： 
无法执行动作“climate/set_hvac_mode” 。 expected HVACMode or one of 'off', 'heat', 'cool', 'heat_cool', 'auto', 'dry', 'fan_only' for dictionary value @ data['hvac_mode']

产品型号：
  美的风管机乐享3

**Comment by mill1000** [comment]
Can you provide full debug logs?

**Comment by muyeyong** [comment]
> Can you provide full debug logs?

Where can I access the full application logs?

**Comment by mill1000** [comment]
There's a "Enable debug logging" button on the integration page or you can add this to your configuration.yaml

```yaml
logger:
  default: warning
  logs:
    custom_components.midea_ac: info
    msmart: debug
```
