### ISSUE TITLE
Can't reuse configurations in configuration.yaml inherented from mac-zhou/midea-ac-py

### ISSUE THREAD

**Issue by troyliu0105** [mill1000/midea-ac-py#47]
Hi, mill1000. Thanks for your work!!! This fork works like a charm!
But I have a minor issue/question about the usage.

When I use mac-zhou's repo, I configure the items by modifying the `configuration.yaml` file like below:
```yaml
climate:
  - platform: midea_ac
    host: 192.168.1.100
    id: 123456789012345
    # v3 need token and k1(key)
    # token: ACEDDA53831AE5DC...(Length 128)
    # k1: CFFA10FC...(Length 64)
```
But after I uninstall mac-zhou's repo, and install your port. HA says that 'Platform support not supported'.
![图片](https://github.com/mill1000/midea-ac-py/assets/5518286/0ddaf97a-4056-4c36-a56e-23eb21646c6c)

I know I can manually add the items in the GUI, but if possible I'd like to all the configurations just stay in one file.
So... any suggestions?
